### PR TITLE
Use HTTPS

### PR DESCRIPTION
**Pull request by TangRufus**
Use HTTPS as https://yarnpkg.com/lang/en/docs/install/ suggested

### CODE REVIEW

**Comment by ocha** [comment]
Thank you for the PR @TangRufus. Looks like https source is not supported buy docker image by default and https repo is not fetched during install. Can you please modify `.travis.yml` and install `apt-transport-https`. I think adding `sudo apt-get install -y apt-transport-https` in `before_install` sections should be good.

**Comment by TangRufus** [comment]
Looks like `sudo apt-get install -y apt-transport-https` is not enough. Any suggestion?

**Comment by TangRufus** [comment]
Tried both:

```
before_install:
  # Pull container from Docker Hub.
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

  - sudo apt-get install -y apt-transport-https
```

```
install:
  # Create a random file to store the container ID.
  - container_id=$(mktemp)

  # Run container detached, with our role mounted inside.
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'

  - if [[ "${distro}" == ubuntu* ]]; then docker exec "$(cat ${container_id})" apt-get -qq update; fi
  - if [[ "${distro}" == ubuntu* ]]; then docker exec "$(cat ${container_id})" apt-get install -y apt-transport-https; fi
```

No luck for both. Any suggestion?

**Comment by ocha** [comment]
Im not sure. I am going to create a branch and experiment there. Usually when I have see https repo not working while http works, it is because of apt missing https support... However it might not be the case here

**Pull request merged**
